/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as ScanIdRouteImport } from './routes/scan_.$id'
import { Route as RestaurantsNewRouteImport } from './routes/restaurants.new'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as ApiDishImageRouteImport } from './routes/api/dish-image'
import { Route as RestaurantsSlugEditRouteImport } from './routes/restaurants.$slug.edit'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanIdRoute = ScanIdRouteImport.update({
  id: '/scan_/$id',
  path: '/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsNewRoute = RestaurantsNewRouteImport.update({
  id: '/restaurants/new',
  path: '/restaurants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDishImageRoute = ApiDishImageRouteImport.update({
  id: '/api/dish-image',
  path: '/api/dish-image',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsSlugEditRoute = RestaurantsSlugEditRouteImport.update({
  id: '/$slug/edit',
  path: '/$slug/edit',
  getParentRoute: () => RestaurantsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/api/dish-image': typeof ApiDishImageRoute
  '/m/$slug': typeof MSlugRoute
  '/restaurants/new': typeof RestaurantsNewRoute
  '/scan/$id': typeof ScanIdRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/restaurants/$slug/edit': typeof RestaurantsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/api/dish-image': typeof ApiDishImageRoute
  '/m/$slug': typeof MSlugRoute
  '/restaurants/new': typeof RestaurantsNewRoute
  '/scan/$id': typeof ScanIdRoute
  '/restaurants': typeof RestaurantsIndexRoute
  '/restaurants/$slug/edit': typeof RestaurantsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/api/dish-image': typeof ApiDishImageRoute
  '/m/$slug': typeof MSlugRoute
  '/restaurants/new': typeof RestaurantsNewRoute
  '/scan_/$id': typeof ScanIdRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/restaurants/$slug/edit': typeof RestaurantsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/pricing'
    | '/privacy'
    | '/scan'
    | '/api/dish-image'
    | '/m/$slug'
    | '/restaurants/new'
    | '/scan/$id'
    | '/restaurants/'
    | '/restaurants/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/pricing'
    | '/privacy'
    | '/scan'
    | '/api/dish-image'
    | '/m/$slug'
    | '/restaurants/new'
    | '/scan/$id'
    | '/restaurants'
    | '/restaurants/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/pricing'
    | '/privacy'
    | '/scan'
    | '/api/dish-image'
    | '/m/$slug'
    | '/restaurants/new'
    | '/scan_/$id'
    | '/restaurants/'
    | '/restaurants/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ScanRoute: typeof ScanRoute
  ApiDishImageRoute: typeof ApiDishImageRoute
  MSlugRoute: typeof MSlugRoute
  RestaurantsNewRoute: typeof RestaurantsNewRoute
  ScanIdRoute: typeof ScanIdRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan_/$id': {
      id: '/scan_/$id'
      path: '/scan/$id'
      fullPath: '/scan/$id'
      preLoaderRoute: typeof ScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/new': {
      id: '/restaurants/new'
      path: '/restaurants/new'
      fullPath: '/restaurants/new'
      preLoaderRoute: typeof RestaurantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dish-image': {
      id: '/api/dish-image'
      path: '/api/dish-image'
      fullPath: '/api/dish-image'
      preLoaderRoute: typeof ApiDishImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$slug/edit': {
      id: '/restaurants/$slug/edit'
      path: '/$slug/edit'
      fullPath: '/restaurants/$slug/edit'
      preLoaderRoute: typeof RestaurantsSlugEditRouteImport
      parentRoute: typeof RestaurantsRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ScanRoute: ScanRoute,
  ApiDishImageRoute: ApiDishImageRoute,
  MSlugRoute: MSlugRoute,
  RestaurantsNewRoute: RestaurantsNewRoute,
  ScanIdRoute: ScanIdRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
